Update build-kernel.yml

diff --git a/.github/workflows/build-kernel.yml b/.github/workflows/build-kernel.yml
--- a/.github/workflows/build-kernel.yml
+++ b/.github/workflows/build-kernel.yml
@@ -12,6 +12,7 @@ jobs:
       CCACHE_HARDLINK: "true"
     steps:
     - uses: actions/checkout@v4
+
     - name: Prepare Configuration
       run: |
         CONFIG_ENV=$(grep -w "CONFIG_ENV" config.env | head -n 1 | cut -d "=" -f 2)
@@ -28,7 +29,6 @@ jobs:
             ENABLE_CCACHE NEED_DTBO BUILD_BOOT_IMG SOURCE_BOOT_IMAGE
             KSU_EXPECTED_SIZE KSU_EXPECTED_HASH REMOVE_UNUSED_PACKAGES
         )
-
         for CONFIG in "${CONFIG_LIST[@]}"; do
             if [[ "$CONFIG" == "EXTRA_CMDS" || "$CONFIG" == "CUSTOM_CMDS" ]]; then
                 echo "$CONFIG=$(grep -w "$CONFIG" "$CONFIG_ENV" | head -n 1 | cut -d ":" -f 2)" >> $GITHUB_ENV
@@ -54,7 +54,7 @@ jobs:
       with:
         swap-size-gb: 10
 
-    - name: Setup build kernel environment
+    - name: Setup environment
       run: |
         echo "BUILD_TIME=$(TZ=Asia/Shanghai date "+%Y%m%d%H%M")" >> $GITHUB_ENV
         echo "DEVICE=$(echo ${{ env.KERNEL_CONFIG }} | sed 's!vendor/!!;s/_defconfig//;s/_user//;s/-perf//')" >> $GITHUB_ENV
@@ -62,247 +62,113 @@ jobs:
         sudo apt-get install git ccache automake flex lzop bison gperf build-essential zip curl zlib1g-dev g++-multilib libxml2-utils bzip2 libbz2-dev libbz2-1.0 libghc-bzlib-dev squashfs-tools pngcrush schedtool dpkg-dev liblz4-tool make optipng maven libssl-dev pwgen libswitch-perl policycoreutils minicom libxml-sax-base-perl libxml-simple-perl bc libc6-dev-i386 lib32ncurses5-dev libx11-dev lib32z-dev libgl1-mesa-dev xsltproc unzip device-tree-compiler python2 python3
         mkdir -p $GITHUB_WORKSPACE/kernel_workspace
 
-    - name: Download Clang-aosp
-      if: env.USE_CUSTOM_CLANG != 'true'
+    - name: Download Toolchains (Clang & GCC)
       run: |
         cd $GITHUB_WORKSPACE/kernel_workspace
-        mkdir clang-aosp
-        wget https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/${{ env.CLANG_BRANCH }}/clang-${{ env.CLANG_VERSION }}.tar.gz
-        tar -C clang-aosp/ -zxvf clang-${{ env.CLANG_VERSION }}.tar.gz
-
-    - name: Download Custom-Clang
-      if: env.USE_CUSTOM_CLANG == 'true'
-      run: |
-        cd $GITHUB_WORKSPACE/kernel_workspace
-        if [[ ${{ env.CUSTOM_CLANG_SOURCE }} =~ git ]]; then
-            if [[ ${{ env.CUSTOM_CLANG_SOURCE }} == *'.tar.gz' ]]; then
-                wget -O clang.tar.gz ${{ env.CUSTOM_CLANG_SOURCE }}
-                mkdir clang-aosp
-                tar -C clang-aosp/ -zxvf clang.tar.gz
-            else
+        # Clang logic
+        if [ "${{ env.USE_CUSTOM_CLANG }}" = "true" ]; then
+            if [[ ${{ env.CUSTOM_CLANG_SOURCE }} == *'.git' ]]; then
                 git clone ${{ env.CUSTOM_CLANG_SOURCE }} -b ${{ env.CUSTOM_CLANG_BRANCH }} clang-aosp --depth=1
+            else
+                wget -O clang.tar.gz ${{ env.CUSTOM_CLANG_SOURCE }} && mkdir clang-aosp && tar -C clang-aosp/ -zxvf clang.tar.gz || (unzip clang.tar.gz -d clang-aosp/)
             fi
         else
-            wget -O clang.zip ${{ env.CUSTOM_CLANG_SOURCE }}
-            mkdir clang-aosp
-            unzip clang.zip -d clang-aosp/
+            mkdir clang-aosp && wget https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/${{ env.CLANG_BRANCH }}/clang-${{ env.CLANG_VERSION }}.tar.gz
+            tar -C clang-aosp/ -zxvf clang-${{ env.CLANG_VERSION }}.tar.gz
         fi
-
-    - name: Download Gcc-aosp
-      if: env.USE_CUSTOM_GCC_64 != 'true' || env.USE_CUSTOM_GCC_32 != 'true'
-      run: |
-        cd $GITHUB_WORKSPACE/kernel_workspace
-        if [ ${{ env.ENABLE_GCC_ARM64 }} = true ]; then
+        
+        # GCC 64 logic
+        if [ "${{ env.ENABLE_GCC_ARM64 }}" = "true" ]; then
             mkdir gcc-64
-            wget -O gcc-aarch64.tar.gz https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/+archive/refs/tags/android-12.1.0_r27.tar.gz
-            tar -C gcc-64/ -zxvf gcc-aarch64.tar.gz
+            wget -O gcc64.tar.gz https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/+archive/refs/tags/android-12.1.0_r27.tar.gz
+            tar -C gcc-64/ -zxvf gcc64.tar.gz
             echo "GCC_64=CROSS_COMPILE=$GITHUB_WORKSPACE/kernel_workspace/gcc-64/bin/aarch64-linux-android-" >> $GITHUB_ENV
         fi
-        if [ ${{ env.ENABLE_GCC_ARM32 }} = true ]; then
+
+        # GCC 32 logic
+        if [ "${{ env.ENABLE_GCC_ARM32 }}" = "true" ]; then
             mkdir gcc-32
-            wget -O gcc-arm.tar.gz https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/+archive/refs/tags/android-12.1.0_r27.tar.gz
-            tar -C gcc-32/ -zxvf gcc-arm.tar.gz
+            wget -O gcc32.tar.gz https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/+archive/refs/tags/android-12.1.0_r27.tar.gz
+            tar -C gcc-32/ -zxvf gcc32.tar.gz
             echo "GCC_32=CROSS_COMPILE_ARM32=$GITHUB_WORKSPACE/kernel_workspace/gcc-32/bin/arm-linux-androideabi-" >> $GITHUB_ENV
         fi
 
-    - name: Download Custom-Gcc
-      if: env.USE_CUSTOM_GCC_64 == 'true' || env.USE_CUSTOM_GCC_32 == 'true'
-      run: |
-        cd $GITHUB_WORKSPACE/kernel_workspace
-        if [ ${{ env.USE_CUSTOM_GCC_64 }} = true ]; then
-          if [[ ${{ env.CUSTOM_GCC_64_SOURCE }} =~ git ]]; then
-              if [[ ${{ env.CUSTOM_GCC_64_SOURCE }} == *'.tar.gz' ]]; then
-                wget -O gcc-64.tar.gz ${{ env.CUSTOM_GCC_64_SOURCE }}
-                mkdir gcc-64
-                tar -C gcc-64/ -zxvf gcc-64.tar.gz
-              else
-                git clone ${{ env.CUSTOM_GCC_64_SOURCE }} -b ${{ env.CUSTOM_GCC_64_BRANCH }} gcc-64 --depth=1
-              fi
-          else
-              wget -O gcc-64.zip ${{ env.CUSTOM_GCC_64_SOURCE }}
-              mkdir gcc-64
-              unzip gcc-64.zip -d gcc-64/
-          fi
-          echo "GCC_64=CROSS_COMPILE=$GITHUB_WORKSPACE/kernel_workspace/gcc-64/bin/${{ env.CUSTOM_GCC_64_BIN }}" >> $GITHUB_ENV
-        fi
-        if [ ${{ env.USE_CUSTOM_GCC_32 }} = true ]; then
-          if [[ ${{ env.CUSTOM_GCC_32_SOURCE }} =~ git ]]; then
-              if [[ ${{ env.CUSTOM_GCC_32_SOURCE }} == *'.tar.gz' ]]; then
-                wget -O gcc-32.tar.gz ${{ env.CUSTOM_GCC_32_SOURCE }}
-                mkdir gcc-32
-                tar -C gcc-32/ -zxvf gcc-32.tar.gz
-              else
-                git clone ${{ env.CUSTOM_GCC_32_SOURCE }} -b ${{ env.CUSTOM_GCC_32_BRANCH }} gcc-32 --depth=1
-              fi
-          else
-            wget -O gcc-32.zip ${{ env.CUSTOM_GCC_32_SOURCE }}
-            mkdir gcc-32
-            unzip gcc-32.zip -d gcc-32/
-          fi
-          echo "GCC_32=CROSS_COMPILE_ARM32=$GITHUB_WORKSPACE/kernel_workspace/gcc-32/bin/${{ env.CUSTOM_GCC_32_BIN }}" >> $GITHUB_ENV
-        fi
-
-    - name: Download mkbootimg tools
-      if: env.BUILD_BOOT_IMG == 'true'
-      run: |
-        cd $GITHUB_WORKSPACE/kernel_workspace
-        git clone https://android.googlesource.com/platform/system/tools/mkbootimg tools -b master-kernel-build-2022 --depth=1
-
-    - name: Download kernel source
+    - name: Download Kernel Source & Tools
       run: |
         cd $GITHUB_WORKSPACE/kernel_workspace
         git clone --recursive ${{ env.KERNEL_SOURCE }} -b ${{ env.KERNEL_SOURCE_BRANCH }} android-kernel --depth=1
-        if [[ ${{ env.ADD_LOCALVERSION_TO_FILENAME }} == 'true' ]]; then
-          echo "LOCALVERSION=$(cat android-kernel/localversion)" >> $GITHUB_ENV
-        else
-          echo "LOCALVERSION=" >> $GITHUB_ENV
-        fi
-
-    - name: Download source boot image
-      if: env.BUILD_BOOT_IMG == 'true'
-      run: |
-        cd $GITHUB_WORKSPACE/kernel_workspace
-        wget -O boot-source.img ${{ env.SOURCE_BOOT_IMAGE }}
-        if [ -f boot-source.img ]; then
-            echo "FORMAT_MKBOOTING=$(echo `tools/unpack_bootimg.py --boot_img=boot-source.img --format mkbootimg`)" >> $GITHUB_ENV
-            echo "HAVE_SOURCE_BOOT_IMAGE=true" >> $GITHUB_ENV
-        fi
+        [ "${{ env.BUILD_BOOT_IMG }}" = "true" ] && git clone https://android.googlesource.com/platform/system/tools/mkbootimg tools -b master-kernel-build-2022 --depth=1
+        [ "${{ env.BUILD_BOOT_IMG }}" = "true" ] && wget -O boot-source.img ${{ env.SOURCE_BOOT_IMAGE }}
 
     - name: Setup KernelSU Next
       if: env.ENABLE_KERNELSU == 'true'
       run: |
         cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
         curl -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/dev/kernel/setup.sh" | bash -s dev
-        
-        # Pindahkan folder ke drivers/kernelsu agar sesuai log error kamu
-        if [ -d "KernelSU-Next" ]; then
-            KSU_VERSION=$(cd KernelSU-Next && expr $(/usr/bin/git rev-list --count HEAD) + 10200)
-            echo "UPLOADNAME=-KernelSU_Next_$KSU_VERSION" >> $GITHUB_ENV
-            mv KernelSU-Next drivers/kernelsu
-        elif [ -d "drivers/KernelSU-Next" ]; then
-            KSU_VERSION=$(cd drivers/KernelSU-Next && expr $(/usr/bin/git rev-list --count HEAD) + 10200)
-            echo "UPLOADNAME=-KernelSU_Next_$KSU_VERSION" >> $GITHUB_ENV
-            mv drivers/KernelSU-Next drivers/kernelsu
-        fi
+        mv KernelSU-Next drivers/kernelsu || mv drivers/KernelSU-Next drivers/kernelsu
+        KSU_VERSION=$(cd drivers/kernelsu && expr $(/usr/bin/git rev-list --count HEAD) + 10200)
+        echo "UPLOADNAME=-KernelSU_Next_$KSU_VERSION" >> $GITHUB_ENV
 
-    - name: Setup Configuration for Kernel
+    - name: Setup Configuration & Fixes
       run: |
         cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
-        
-        # FIX 1: Suntik definisi syscall_fn_t yang hilang di Kernel 4.9
+        # FIX syscall_fn_t for Kernel 4.9
         if [ -f "drivers/kernelsu/hook/syscall_hook.h" ]; then
-            echo "Suntik fix syscall_fn_t..."
             sed -i '1i #include <linux/ptrace.h>' drivers/kernelsu/hook/syscall_hook.h
             sed -i '2i typedef long (*syscall_fn_t)(const struct pt_regs *);' drivers/kernelsu/hook/syscall_hook.h
         fi
-
-        # FIX 2: Daftarkan folder ke Makefile drivers
+        # Integrasi Makefile
         sed -i '/obj-y += kernelsu\//d' drivers/Makefile
-        sed -i '/obj-y += KernelSU-Next\//d' drivers/Makefile
         echo "obj-y += kernelsu/" >> drivers/Makefile
-
-        # FIX 3: Mencegah konflik redefinisi PR_SET_VMA & vfs_statfs
-        if [ -f "drivers/kernelsu/core/ksu_setup.c" ]; then
-            sed -i 's/PR_SET_VMA/PR_SET_VMA_KSU/g' drivers/kernelsu/core/ksu_setup.c || true
-        fi
-        if [ -f "drivers/kernelsu/core/hooks.c" ]; then
-            sed -i 's/vfs_statfs/ksu_vfs_statfs/g' drivers/kernelsu/core/hooks.c || true
-        fi
-
-        # Setup Config File
+        # Patch PR_SET_VMA
+        sed -i 's/PR_SET_VMA/PR_SET_VMA_KSU/g' drivers/kernelsu/core/ksu_setup.c || true
+        
+        # Defconfig adjustments
         CONF="arch/${{ env.ARCH }}/configs/${{ env.KERNEL_CONFIG }}"
-        if [ "${{ env.ENABLE_KERNELSU }}" = "true" ]; then
-            sed -i '/CONFIG_KSU/d' $CONF
-            echo "CONFIG_KSU=y" >> $CONF
-        fi
-
-        if [ "${{ env.ADD_KPROBES_CONFIG }}" = "true" ]; then
-            echo "CONFIG_MODULES=y" >> $CONF
-            echo "CONFIG_KPROBES=y" >> $CONF
-            echo "CONFIG_HAVE_KPROBES=y" >> $CONF
-            echo "CONFIG_KPROBE_EVENTS=y" >> $CONF
-        fi
-
-        if [ "${{ env.ADD_OVERLAYFS_CONFIG }}" = "true" ]; then
-            echo "CONFIG_OVERLAY_FS=y" >> $CONF
-        fi
-
-        if [ "${{ env.DISABLE-LTO }}" = "true" ]; then
-            sed -i 's/CONFIG_LTO=y/CONFIG_LTO=n/' $CONF
-            sed -i 's/CONFIG_LTO_CLANG=y/CONFIG_LTO_CLANG=n/' $CONF
-            sed -i 's/CONFIG_THINLTO=y/CONFIG_THINLTO=n/' $CONF
-            echo "CONFIG_LTO_NONE=y" >> $CONF
-        fi
-
-        if [ "${{ env.DISABLE_CC_WERROR }}" = "true" ]; then
-            echo "CONFIG_CC_WERROR=n" >> $CONF
-        fi
+        echo "CONFIG_KSU=y" >> $CONF
+        [ "${{ env.ADD_KPROBES_CONFIG }}" = "true" ] && (echo "CONFIG_MODULES=y" >> $CONF; echo "CONFIG_KPROBES=y" >> $CONF; echo "CONFIG_HAVE_KPROBES=y" >> $CONF; echo "CONFIG_KPROBE_EVENTS=y" >> $CONF)
+        [ "${{ env.ADD_OVERLAYFS_CONFIG }}" = "true" ] && echo "CONFIG_OVERLAY_FS=y" >> $CONF
+        [ "${{ env.DISABLE_CC_WERROR }}" = "true" ] && echo "CONFIG_CC_WERROR=n" >> $CONF
 
     - name: Setup ccache
-      if: env.ENABLE_CCACHE == 'true'
       uses: hendrikmuhs/ccache-action@v1.2
       with:
-        key: build-kernel-${{ env.DEVICE }}${{ env.LOCALVERSION }}${{ env.UPLOADNAME }}
+        key: build-kernel-${{ env.DEVICE }}${{ env.UPLOADNAME }}
         max-size: 2G
 
-    - name: Build kernel
+    - name: Build Kernel
       run: |
         cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
         export PATH=$GITHUB_WORKSPACE/kernel_workspace/clang-aosp/bin:$PATH
-        export KBUILD_BUILD_HOST=Github-Action
-        export KBUILD_BUILD_USER=$(echo ${{ github.actor }} | tr A-Z a-z)
-        
-        # Build defconfig
         make O=out ARCH=${{ env.ARCH }} ${{ env.KERNEL_CONFIG }}
-        
-        # Build Kernel
-        if [ ${{ env.ENABLE_CCACHE }} = true ]; then
-            make -j$(nproc --all) CC="ccache clang" O=out ARCH=${{ env.ARCH }} ${{ env.CUSTOM_CMDS }} ${{ env.EXTRA_CMDS }} ${{ env.GCC_64 }} ${{ env.GCC_32 }}
-        else
-            make -j$(nproc --all) CC=clang O=out ARCH=${{ env.ARCH }} ${{ env.CUSTOM_CMDS }} ${{ env.EXTRA_CMDS }} ${{ env.GCC_64 }} ${{ env.GCC_32 }}
-        fi
+        make -j$(nproc --all) CC="ccache clang" O=out ARCH=${{ env.ARCH }} ${{ env.CUSTOM_CMDS }} ${{ env.EXTRA_CMDS }} ${{ env.GCC_64 }} ${{ env.GCC_32 }}
 
-    - name: Check a kernel output files
-      run: |
-       cd $GITHUB_WORKSPACE/kernel_workspace
-       if [ -f android-kernel/out/arch/${{ env.ARCH }}/boot/${{ env.KERNEL_IMAGE_NAME }} ]; then
-           echo "CHECK_FILE_IS_OK=true" >> $GITHUB_ENV
-       else
-           echo "Kernel output file is empty"
-           exit 1
-       fi
-
-    - name: Make Anykernel3
-      if: env.CHECK_FILE_IS_OK == 'true' && env.USE_CUSTOM_ANYKERNEL3 != 'true'
+    - name: Process Boot Image (mkbootimg)
+      if: env.BUILD_BOOT_IMG == 'true'
       run: |
         cd $GITHUB_WORKSPACE/kernel_workspace
-        git clone https://github.com/osm0sis/AnyKernel3 --depth=1 AnyKernel3
-        sed -i 's/do.devicecheck=1/do.devicecheck=0/g' AnyKernel3/anykernel.sh
-        sed -i 's!BLOCK=/dev/block/platform/omap/omap_hsmmc.0/by-name/boot;!BLOCK=auto;!g' AnyKernel3/anykernel.sh
-        sed -i 's/IS_SLOT_DEVICE=0;/is_slot_device=auto;/g' AnyKernel3/anykernel.sh
-        cp android-kernel/out/arch/${{ env.ARCH }}/boot/${{ env.KERNEL_IMAGE_NAME }} AnyKernel3/
-        [ -f android-kernel/out/arch/${{ env.ARCH }}/boot/dtbo.img ] && cp android-kernel/out/arch/${{ env.ARCH }}/boot/dtbo.img AnyKernel3/
-        rm -rf AnyKernel3/.git* AnyKernel3/README.md
+        IMG="android-kernel/out/arch/${{ env.ARCH }}/boot/${{ env.KERNEL_IMAGE_NAME }}"
+        if [ -f "$IMG" ]; then
+            python3 tools/unpack_bootimg.py --boot_img boot-source.img --out out_boot
+            cp $IMG out_boot/kernel
+            # Ambil argumen asli dari boot-source
+            ARGS=$(python3 tools/unpack_bootimg.py --boot_img boot-source.img --format mkbootimg)
+            python3 tools/mkbootimg.py $ARGS -o boot-ksu.img
+        fi
 
-    - name: Make Custom-Anykernel3
-      if: env.CHECK_FILE_IS_OK == 'true' && env.USE_CUSTOM_ANYKERNEL3 == 'true'
+    - name: Prepare AnyKernel3
       run: |
         cd $GITHUB_WORKSPACE/kernel_workspace
-        if [[ ${{ env.CUSTOM_ANYKERNEL3_SOURCE }} =~ git ]]; then
-            git clone ${{ env.CUSTOM_ANYKERNEL3_SOURCE }} -b ${{ env.CUSTOM_ANYKERNEL3_BRANCH }} --depth=1 AnyKernel3
-        else
-            wget -O AnyKernel3.zip ${{ env.CUSTOM_ANYKERNEL3_SOURCE }}
-            mkdir AnyKernel3 && unzip AnyKernel3.zip -d AnyKernel3/
-        fi
-        cp android-kernel/out/arch/${{ env.ARCH }}/boot/${{ env.KERNEL_IMAGE_NAME }} AnyKernel3/
-        [ -f android-kernel/out/arch/${{ env.ARCH }}/boot/dtbo.img ] && cp android-kernel/out/arch/${{ env.ARCH }}/boot/dtbo.img AnyKernel3/
-        rm -rf AnyKernel3/.git* AnyKernel3/README.md
+        git clone https://github.com/osm0sis/AnyKernel3 --depth=1 AK3
+        cp android-kernel/out/arch/${{ env.ARCH }}/boot/${{ env.KERNEL_IMAGE_NAME }} AK3/
+        [ -f android-kernel/out/arch/${{ env.ARCH }}/boot/dtbo.img ] && cp android-kernel/out/arch/${{ env.ARCH }}/boot/dtbo.img AK3/
+        rm -rf AK3/.git*
 
-    - name: Upload Artifacts
-      if: env.CHECK_FILE_IS_OK == 'true'
+    - name: Upload All Artifacts
       uses: actions/upload-artifact@v4
       with:
-        name: Kernel-${{ env.DEVICE }}-${{ env.BUILD_TIME }}
+        name: Kernel-Result-${{ env.DEVICE }}-${{ env.BUILD_TIME }}
         path: |
-          kernel_workspace/AnyKernel3/*
+          kernel_workspace/AK3/*
+          kernel_workspace/boot-ksu.img
           kernel_workspace/android-kernel/out/arch/${{ env.ARCH }}/boot/${{ env.KERNEL_IMAGE_NAME }}
